name: CI Pipeline

on:  #Eventos a disparar
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:   # Que se ejecute de la uI

env:
  NODE_VERSION: "22"  
  APP_NAME: cron-ticker-v2

jobs:
  build:
    runs-on: ubuntu-latest

    env: #job build
      BUILD_DIR: workflow_dispatch

    steps:
      - uses: actions/checkout@v4

      - name: Show variables
        run: 
          echo "App: ${{env.APP_NAME}}, Node: ${{env.NODE_VERSION}}"

      - name: Build
        run: npm run build
        env:
          APP_VERSION: "3.0.0"

 


